#!/usr/bin/env python3
"""Build all _generated/ indexes from the raw mirror. Deterministic; never hand-edit outputs.

Inputs:  raw/data/github/*/{issues,pulls}/**/*.md  (sentinel format, see AGENTS.md)
         raw/data/w3c-api/specifications/*.json
         tools/data/people.yml
Outputs: _generated/resolutions-index.{md,jsonl}
         _generated/issues-index.{md,jsonl}
         _generated/meetings-index.{md,jsonl}
         _generated/spec-status-index.md
         _generated/by-spec/<label>.md
         _generated/people-activity.jsonl
         _generated/people-unmapped.txt

Resolution extraction: lines in css-meeting-bot comments matching RESOLVED_LINE_RE.
Known format variants 2017-2026: with/without leading "* ", with/without backticks,
"RESOLUTION:" in some early comments. The resolution *date* is the bot comment's
created_at (bot bodies carry no date). Sanity check: as of 2026-07 about 3,324 issues
contain RESOLVED text; a large deviation means the extraction regex drifted.
"""

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GITHUB = ROOT / "raw" / "data" / "github"
W3C = ROOT / "raw" / "data" / "w3c-api" / "specifications"
GEN = ROOT / "_generated"
BOT = "css-meeting-bot"
EXPECTED_RESOLVED_ISSUES = 3324  # 2026-07 baseline for the sanity check

SENTINEL_RE = re.compile(
    r"^<!-- comment id=(\d+) author=(\S+) created=(\S+) url=(\S+?)( resolution=true)? -->$",
    re.M,
)
RESOLVED_LINE_RE = re.compile(r"^\s*(?:[*-]\s*)?`?(?:RESOLVED|RESOLUTION):\s*(.+?)`?\s*$", re.M)
IRC_NICK_RE = re.compile(r"^\s*<([A-Za-z_][A-Za-z0-9_.\-\[\]|]{1,30})>\s", re.M)
HTML_TAGS = {"details", "summary", "p", "br", "b", "i", "hr", "ins", "del", "img", "a"}
SPEC_LABEL_RE = re.compile(r"^[a-z][a-z0-9]*(-[a-z0-9]+)*-\d+$")

HEADER = "<!-- generated by tools/build_indexes.py — do not edit -->\n"


def parse_mirror(path: Path) -> dict:
    text = path.read_text()
    m = re.match(r"\A---\n(.*?\n)---\n", text, re.S)
    meta = {}
    for line in m.group(1).splitlines():
        k, _, v = line.partition(":")
        meta[k.strip()] = json.loads(v.strip()) if v.strip() else None
    parts = SENTINEL_RE.split(text[m.end():])
    comments = []
    for i in range(1, len(parts), 6):
        cid, author, created, url, _res, chunk = parts[i : i + 6]
        lines = chunk.strip("\n").split("\n")
        comments.append(
            {
                "id": int(cid),
                "author": author,
                "created_at": created,
                "url": url,
                "body": "\n".join(lines[1:]).strip("\n"),
            }
        )
    return {"meta": meta, "comments": comments}


def jsonl(rows: list) -> str:
    return "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows)


def main() -> None:
    issues_rows, resolutions, activity = [], [], defaultdict(Counter)
    meetings = defaultdict(lambda: {"topics": 0, "issues": set(), "resolutions": 0})
    by_spec = defaultdict(list)
    resolved_issue_count = 0

    files = sorted(GITHUB.glob("*/issues/*/*.md")) + sorted(GITHUB.glob("*/pulls/*/*.md"))
    if not files:
        print("[build_indexes] no mirror files found — run sync_issues.py first")
        sys.exit(1)

    for path in files:
        kind = "pull" if path.parent.parent.name == "pulls" else "issue"
        doc = parse_mirror(path)
        meta, comments = doc["meta"], doc["comments"]
        n, labels = meta["number"], meta.get("labels") or []
        spec_labels = [l for l in labels if SPEC_LABEL_RE.match(l)]

        issues_rows.append(
            {
                "number": n,
                "kind": kind,
                "state": meta.get("state"),
                "title": meta.get("title"),
                "labels": labels,
                "author": meta.get("author"),
                "created_at": meta.get("created_at"),
                "closed_at": meta.get("closed_at"),
                "comments": meta.get("comments"),
                "has_resolution": bool(meta.get("has_resolution")),
                "url": meta.get("url"),
            }
        )
        activity[meta.get("author") or "ghost"]["issues_authored"] += 1
        if meta.get("has_resolution"):
            resolved_issue_count += 1
        for l in spec_labels:
            by_spec[l].append(
                ((meta.get("created_at") or "")[:10], f"opened #{n}: {meta.get('title')}")
            )

        for c in comments:
            activity[c["author"]]["comments"] += 1
            if c["author"] != BOT:
                continue
            date = (c["created_at"] or "")[:10]
            meetings[date]["topics"] += 1
            meetings[date]["issues"].add(n)
            for nick in IRC_NICK_RE.findall(c["body"]):
                if nick.lower() not in HTML_TAGS:
                    activity[nick]["irc_lines"] += 1
            for res in RESOLVED_LINE_RE.findall(c["body"]):
                resolutions.append(
                    {
                        "date": date,
                        "issue": n,
                        "kind": kind,
                        "labels": spec_labels,
                        "title": meta.get("title"),
                        "resolution": res.strip(),
                        "comment_url": c["url"],
                    }
                )
                meetings[date]["resolutions"] += 1
                for l in spec_labels:
                    by_spec[l].append((date, f"RESOLVED #{n}: {res.strip()}"))

    GEN.mkdir(exist_ok=True)
    (GEN / "by-spec").mkdir(exist_ok=True)

    # --- resolutions-index
    resolutions.sort(key=lambda r: (r["date"], r["issue"], r["comment_url"], r["resolution"]))
    (GEN / "resolutions-index.jsonl").write_text(jsonl(resolutions))
    md = [HEADER + "# Resolutions index", "", "`date | issue | labels | resolution | permalink`", ""]
    md += [
        f"- {r['date']} | #{r['issue']} | {','.join(r['labels']) or '-'} | "
        f"RESOLVED: {r['resolution']} | {r['comment_url']}"
        for r in resolutions
    ]
    (GEN / "resolutions-index.md").write_text("\n".join(md) + "\n")

    # --- issues-index
    issues_rows.sort(key=lambda r: (r["kind"], r["number"]))
    (GEN / "issues-index.jsonl").write_text(jsonl(issues_rows))
    md = [HEADER + "# Issues index", "", "`number | state | labels | title (R = has resolution)`", ""]
    md += [
        f"- #{r['number']} {'PR ' if r['kind'] == 'pull' else ''}{r['state']} "
        f"[{','.join(r['labels']) or '-'}] {r['title']}{' R' if r['has_resolution'] else ''}"
        for r in issues_rows
    ]
    (GEN / "issues-index.md").write_text("\n".join(md) + "\n")

    # --- meetings-index
    mrows = [
        {
            "date": d,
            "type_guess": "f2f" if v["topics"] >= 13 else "telecon",
            "topics": v["topics"],
            "resolutions": v["resolutions"],
            "issues": sorted(v["issues"]),
        }
        for d, v in sorted(meetings.items())
    ]
    (GEN / "meetings-index.jsonl").write_text(jsonl(mrows))
    md = [HEADER + "# Meetings index", "", "`date | type? | topics | resolutions | issues`", ""]
    md += [
        f"- {m['date']} | {m['type_guess']} | {m['topics']} topics | "
        f"{m['resolutions']} resolutions | " + " ".join(f"#{i}" for i in m["issues"])
        for m in mrows
    ]
    (GEN / "meetings-index.md").write_text("\n".join(md) + "\n")

    # --- by-spec digests
    open_by_label = Counter()
    for r in issues_rows:
        if r["state"] == "open" and r["kind"] == "issue":
            for l in r["labels"]:
                open_by_label[l] += 1
    for label, entries in sorted(by_spec.items()):
        entries.sort()
        lines = [HEADER + f"# {label} — chronological digest", ""]
        lines += [f"- {d} {text}" for d, text in entries]
        (GEN / "by-spec" / f"{label}.md").write_text("\n".join(lines) + "\n")

    # --- spec-status-index (needs w3c-api snapshots)
    md = [
        HEADER + "# Spec status index",
        "",
        "`shortname | maturity | latest TR | open issues | wiki page`",
        "",
    ]
    for f in sorted(W3C.glob("*.json")):
        spec = json.loads(f.read_text())
        vs = spec.get("versions") or []
        latest = vs[-1] if vs else {}
        short = spec["shortname"]
        wiki_page = (ROOT / "wiki" / "specs" / f"{short}.md").exists()
        md.append(
            f"- {short} | {latest.get('maturity', 'ED')} | {latest.get('date', '-')} | "
            f"{open_by_label.get(short, 0)} open | {'yes' if wiki_page else 'no'}"
        )
    (GEN / "spec-status-index.md").write_text("\n".join(md) + "\n")

    # --- people activity + unmapped
    sys.path.insert(0, str(Path(__file__).parent))
    from extract_people import load_people  # noqa: E402

    people = load_people()
    mapped = set()
    for p in people:
        mapped.add(p.get("github", "").lower())
        mapped.update(n.lower() for n in p.get("irc_nicks", []))
    arows = [
        {"key": k, **dict(sorted(v.items()))}
        for k, v in sorted(activity.items(), key=lambda kv: (-sum(kv[1].values()), kv[0]))
    ]
    (GEN / "people-activity.jsonl").write_text(jsonl(arows))
    unmapped = [
        f"{sum(v.values()):6d}  {k}"
        for k, v in sorted(activity.items(), key=lambda kv: (-sum(kv[1].values()), kv[0]))
        if k.lower() not in mapped and k != BOT and not k.endswith("[bot]")
    ][:200]
    (GEN / "people-unmapped.txt").write_text("\n".join(unmapped) + "\n")

    # --- sanity check
    n_res_files = resolved_issue_count
    drift = abs(n_res_files - EXPECTED_RESOLVED_ISSUES) / EXPECTED_RESOLVED_ISSUES
    print(
        f"[build_indexes] {len(files)} mirror files, {len(resolutions)} resolutions, "
        f"{n_res_files} items with RESOLVED (baseline {EXPECTED_RESOLVED_ISSUES}), "
        f"{len(mrows)} meeting dates"
    )
    if n_res_files >= EXPECTED_RESOLVED_ISSUES and drift > 0.5:
        print("[build_indexes] WARNING: RESOLVED count drifted >50% from baseline — check regexes")


if __name__ == "__main__":
    main()
