#!/usr/bin/env python3
"""Build all _generated/ indexes from the raw mirror. Deterministic; never hand-edit outputs.

Inputs:  raw/data/github/*/{issues,pulls}/**/*.md  (sentinel format, see AGENTS.md)
         raw/data/w3c-api/specifications/*.json
         tools/data/people.yml
Outputs: _generated/resolutions-index.{md,jsonl}
         _generated/issues-index.{md,jsonl}
         _generated/meetings-index.{md,jsonl}
         _generated/spec-status-index.md
         _generated/by-spec/<label>.md
         _generated/people-activity.jsonl
         _generated/people-unmapped.txt

Resolution extraction: lines matching RESOLVED_LINE_RE in comments. Bot comments
(css-meeting-bot, 2017-04-) are official telecon/F2F minutes; non-bot matches are
kept as source=manual (hand-pasted minutes 2015-2017, async resolutions) with lower
trust. Blockquoted lines never match (quotations). The resolution *date* is the
comment's created_at (bodies carry no date). Known format variants: with/without
leading "* ", with/without backticks, "RESOLUTION:" in early comments.

Sanity baseline (corpus-measured 2026-07): 2,578 items yield structured resolutions;
2,711 files contain the literal string at all (rest = prose/body mentions). The
research-time figure of 3,324 came from GitHub's search index and overcounts.
A future count *below* the baseline means the regex or mirror regressed.
"""

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GITHUB = ROOT / "raw" / "data" / "github"
W3C = ROOT / "raw" / "data" / "w3c-api" / "specifications"
WWW_STYLE = ROOT / "raw" / "data" / "www-style"
GEN = ROOT / "_generated"
BOT = "css-meeting-bot"
EXPECTED_RESOLVED_ISSUES = 2578  # corpus-measured 2026-07 baseline (see docstring)

# www-style minutes emails (2008-2017, pre-bot). RESOLVED lines wrap: the rule
# (also stated in AGENTS.md, R1) is "join the RESOLVED line with immediately
# following continuation lines — non-empty, indented, not a new bullet, not a
# heading underline — then collapse every whitespace run to a single space".
MINUTES_SUBJECT_RE = re.compile(r"^\[CSSWG\]\s+(?:Minutes|Resolutions)\b", re.I)
EMAIL_RESOLVED_RE = re.compile(r"^(\s*)(?:[*-]\s*)?(?:RESOLVED|RESOLUTION):\s*(.*)$")
CONTINUATION_RE = re.compile(r"^\s+\S")
BULLET_OR_RULE_RE = re.compile(r"^\s*(?:[*-]\s|-{3,}\s*$|={3,}\s*$)")
HEADING_RE = re.compile(r"^(\S.*)\n\s*-{3,}\s*$", re.M)
MEETING_DATE_RE = re.compile(r"\b(\d{4}-\d{2}-\d{2})\b")
PARTIAL_DATE_RE = re.compile(r"\b(\d{4}-\d{2})\b")

SENTINEL_RE = re.compile(
    r"^<!-- comment id=(\d+) author=(\S+) created=(\S+) url=(\S+?)( resolution=true)? -->$",
    re.M,
)
RESOLVED_LINE_RE = re.compile(r"^\s*(?:[*-]\s*)?`?(?:RESOLVED|RESOLUTION):\s*(.+?)`?\s*$", re.M)
IRC_NICK_RE = re.compile(r"^\s*<([A-Za-z_][A-Za-z0-9_.\-\[\]|]{1,30})>\s", re.M)
HTML_TAGS = {"details", "summary", "p", "br", "b", "i", "hr", "ins", "del", "img", "a"}
SPEC_LABEL_RE = re.compile(r"^[a-z][a-z0-9]*(-[a-z0-9]+)*-\d+$")

HEADER = "<!-- generated by tools/build_indexes.py — do not edit -->\n"


def parse_mirror(path: Path) -> dict:
    text = path.read_text()
    m = re.match(r"\A---\n(.*?\n)---\n", text, re.S)
    meta = {}
    for line in m.group(1).splitlines():
        k, _, v = line.partition(":")
        meta[k.strip()] = json.loads(v.strip()) if v.strip() else None
    parts = SENTINEL_RE.split(text[m.end():])
    comments = []
    for i in range(1, len(parts), 6):
        cid, author, created, url, _res, chunk = parts[i : i + 6]
        lines = chunk.strip("\n").split("\n")
        comments.append(
            {
                "id": int(cid),
                "author": author,
                "created_at": created,
                "url": url,
                "body": "\n".join(lines[1:]).strip("\n"),
            }
        )
    return {"meta": meta, "comments": comments}


def jsonl(rows: list) -> str:
    return "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows)


def extract_email_resolutions(body: str) -> list[str]:
    """Apply the continuation-joining rule documented above."""
    lines = body.split("\n")
    out = []
    i = 0
    while i < len(lines):
        m = EMAIL_RESOLVED_RE.match(lines[i])
        if not m:
            i += 1
            continue
        parts = [m.group(2)]
        i += 1
        while (
            i < len(lines)
            and lines[i].strip()
            and CONTINUATION_RE.match(lines[i])
            and not BULLET_OR_RULE_RE.match(lines[i])
            and not EMAIL_RESOLVED_RE.match(lines[i])
        ):
            parts.append(lines[i])
            i += 1
        text = re.sub(r"\s+", " ", " ".join(parts)).strip()
        if text:
            out.append(text)
    return out


def normalize_subject(subject: str) -> str:
    s = subject
    while True:
        stripped = re.sub(r"(?i)^\s*(?:re(?:\[\d+\])?|fwd?|aw):\s*", "", s)
        if stripped == s:
            break
        s = stripped
    return re.sub(r"\s+", " ", s).strip().casefold()


def meeting_type_from_subject(subject: str) -> str:
    s = subject.lower()
    if "tpac" in s:
        return "tpac"
    if "f2f" in s:
        return "f2f"
    if "breakout" in s:
        return "breakout"
    return "telecon"


def scan_www_style() -> tuple[list, list, list]:
    """Read per-month sidecars; parse minutes bodies for resolutions.

    Returns (minutes_rows, email_resolutions, all_message_rows)."""
    minutes_rows, email_resolutions, messages = [], [], []
    for sidecar in sorted(WWW_STYLE.glob("*/.messages.jsonl")):
        month = sidecar.parent.name
        for line in sidecar.read_text().splitlines():
            row = json.loads(line)
            row["month"] = month
            messages.append(row)
            subject = row.get("subject") or ""
            if not MINUTES_SUBJECT_RE.match(subject):
                continue
            m = MEETING_DATE_RE.search(subject)
            uncertain = False
            if m:
                meeting_date = m.group(1)
            else:
                pm = PARTIAL_DATE_RE.search(subject)
                meeting_date = (pm.group(1) if pm else (row.get("date") or "")[:10]) or None
                uncertain = True
            body = (sidecar.parent / f"{row['nnnn']}.md").read_text().split("\n---\n", 1)[1]
            topics = HEADING_RE.findall(body)
            # minutes mails repeat each RESOLVED in the summary AND the log,
            # sometimes with punctuation drift — dedupe within one mail on an
            # alphanumeric-only key, keeping the first occurrence's text
            seen_keys, resolutions = set(), []
            for res in extract_email_resolutions(body):
                key = re.sub(r"[^a-z0-9]+", "", res.casefold())
                if key not in seen_keys:
                    seen_keys.add(key)
                    resolutions.append(res)
            minutes_rows.append(
                {
                    "date": meeting_date,
                    "date_uncertain": uncertain,
                    "type": meeting_type_from_subject(subject),
                    "subject": subject,
                    "topics": len(topics),
                    "resolutions": len(resolutions),
                    "archived_at": row.get("archived_at"),
                }
            )
            for res in resolutions:
                email_resolutions.append(
                    {
                        "date": meeting_date,
                        "issue": None,
                        "kind": "email",
                        "source": "minutes-email",
                        "labels": [],
                        "title": subject,
                        "resolution": res,
                        "comment_url": row.get("archived_at"),
                    }
                )
    return minutes_rows, email_resolutions, messages


def main() -> None:
    issues_rows, resolutions, activity = [], [], defaultdict(Counter)
    meetings = defaultdict(
        lambda: {
            "topics": 0,
            "issues": set(),
            "resolutions": 0,
            "sources": set(),
            "minutes_urls": [],
            "type": None,
        }
    )
    by_spec = defaultdict(list)
    resolved_issue_count = 0

    files = sorted(GITHUB.glob("*/issues/*/*.md")) + sorted(GITHUB.glob("*/pulls/*/*.md"))
    if not files:
        print("[build_indexes] no mirror files found — run sync_issues.py first")
        sys.exit(1)

    for path in files:
        kind = "pull" if path.parent.parent.name == "pulls" else "issue"
        doc = parse_mirror(path)
        meta, comments = doc["meta"], doc["comments"]
        n, labels = meta["number"], meta.get("labels") or []
        spec_labels = [l for l in labels if SPEC_LABEL_RE.match(l)]

        issues_rows.append(
            {
                "number": n,
                "kind": kind,
                "state": meta.get("state"),
                "title": meta.get("title"),
                "labels": labels,
                "author": meta.get("author"),
                "created_at": meta.get("created_at"),
                "closed_at": meta.get("closed_at"),
                "comments": meta.get("comments"),
                "has_resolution": bool(meta.get("has_resolution")),
                "async_resolution": any(l.startswith("Async Resolution") for l in labels),
                "url": meta.get("url"),
            }
        )
        activity[meta.get("author") or "ghost"]["issues_authored"] += 1
        for l in spec_labels:
            by_spec[l].append(
                ((meta.get("created_at") or "")[:10], f"opened #{n}: {meta.get('title')}")
            )

        item_has_res = False
        for c in comments:
            activity[c["author"]]["comments"] += 1
            is_bot = c["author"] == BOT
            date = (c["created_at"] or "")[:10]
            if is_bot:
                meetings[date]["topics"] += 1
                meetings[date]["issues"].add(n)
                meetings[date]["sources"].add("bot")
                for nick in IRC_NICK_RE.findall(c["body"]):
                    if nick.lower() not in HTML_TAGS:
                        activity[nick]["irc_lines"] += 1
            # bot comments = official telecon/F2F minutes; non-bot matches are
            # hand-pasted minutes (pre-2017) or async resolutions — kept with
            # source=manual and a caveat: `date` is the comment date, and the
            # text may be a quotation rather than a new resolution.
            for res in RESOLVED_LINE_RE.findall(c["body"]):
                item_has_res = True
                resolutions.append(
                    {
                        "date": date,
                        "issue": n,
                        "kind": kind,
                        "source": "bot" if is_bot else "manual",
                        "labels": spec_labels,
                        "title": meta.get("title"),
                        "resolution": res.strip(),
                        "comment_url": c["url"],
                    }
                )
                if is_bot:
                    meetings[date]["resolutions"] += 1
                for l in spec_labels:
                    by_spec[l].append((date, f"RESOLVED #{n}: {res.strip()}"))
        if item_has_res:
            resolved_issue_count += 1

    # --- www-style minutes emails (pre-bot era)
    minutes_rows, email_resolutions, ws_messages = scan_www_style()
    resolutions += email_resolutions
    for mr in minutes_rows:
        if not mr["date"] or len(mr["date"]) < 10:
            continue  # partial dates stay out of the meetings merge
        mt = meetings[mr["date"]]
        mt["sources"].add("minutes-email")
        mt["minutes_urls"].append(mr["archived_at"])
        mt["type"] = mt["type"] or mr["type"]
        if "bot" not in mt["sources"]:  # bot data wins where both exist
            mt["topics"] = max(mt["topics"], mr["topics"])
            mt["resolutions"] += mr["resolutions"]

    GEN.mkdir(exist_ok=True)
    (GEN / "by-spec").mkdir(exist_ok=True)

    # --- resolutions-index
    resolutions.sort(
        key=lambda r: (r["date"] or "", r["issue"] or 0, r["comment_url"] or "", r["resolution"])
    )
    (GEN / "resolutions-index.jsonl").write_text(jsonl(resolutions))
    md = [
        HEADER + "# Resolutions index",
        "",
        "`date | issue | labels | resolution | permalink`",
        "(manual) = hand-pasted minutes or async resolution: date is the comment date,",
        "and the text may quote an existing resolution — verify at the permalink.",
        "",
    ]
    md += [
        f"- {r['date']} | {'#' + str(r['issue']) if r['issue'] else 'email'} | "
        f"{','.join(r['labels']) or '-'} | RESOLVED: {r['resolution']}"
        f"{' (' + r['source'] + ')' if r['source'] != 'bot' else ''} | {r['comment_url']}"
        for r in resolutions
    ]
    (GEN / "resolutions-index.md").write_text("\n".join(md) + "\n")

    # --- issues-index
    issues_rows.sort(key=lambda r: (r["kind"], r["number"]))
    (GEN / "issues-index.jsonl").write_text(jsonl(issues_rows))
    md = [HEADER + "# Issues index", "", "`number | state | labels | title (R = has resolution)`", ""]
    md += [
        f"- #{r['number']} {'PR ' if r['kind'] == 'pull' else ''}{r['state']} "
        f"[{','.join(r['labels']) or '-'}] {r['title']}{' R' if r['has_resolution'] else ''}"
        for r in issues_rows
    ]
    (GEN / "issues-index.md").write_text("\n".join(md) + "\n")

    # --- meetings-index (bot comments 2017- merged with minutes emails 2008-17)
    mrows = [
        {
            "date": d,
            "type_guess": v["type"] or ("f2f" if v["topics"] >= 13 else "telecon"),
            "topics": v["topics"],
            "resolutions": v["resolutions"],
            "sources": sorted(v["sources"]),
            "issues": sorted(v["issues"]),
            "minutes_urls": v["minutes_urls"],
        }
        for d, v in sorted(meetings.items())
    ]
    (GEN / "meetings-index.jsonl").write_text(jsonl(mrows))
    md = [HEADER + "# Meetings index", "", "`date | type? | topics | resolutions | sources | issues`", ""]
    md += [
        f"- {m['date']} | {m['type_guess']} | {m['topics']} topics | "
        f"{m['resolutions']} resolutions | {'+'.join(m['sources'])} | "
        + (" ".join(f"#{i}" for i in m["issues"]) or " ".join(m["minutes_urls"]))
        for m in mrows
    ]
    (GEN / "meetings-index.md").write_text("\n".join(md) + "\n")

    # --- www-style minutes index + thread summary
    minutes_rows.sort(key=lambda r: (r["date"] or "", r["archived_at"] or ""))
    (GEN / "www-style-minutes-index.jsonl").write_text(jsonl(minutes_rows))
    md = [HEADER + "# www-style minutes index (2008-2017 pre-bot era)", "",
          "`meeting date | subject | archived-at`", ""]
    md += [
        f"- {r['date'] or '?'}{' (uncertain)' if r['date_uncertain'] else ''} | "
        f"{r['subject']} | {r['archived_at']}"
        for r in minutes_rows
    ]
    (GEN / "www-style-minutes-index.md").write_text("\n".join(md) + "\n")

    if ws_messages:
        by_id = {m["message_id"]: m for m in ws_messages if m.get("message_id")}
        roots: dict[str, dict] = {}
        for m in ws_messages:
            cur, hops = m, 0
            while cur.get("in_reply_to") in by_id and hops < 100:
                cur, hops = by_id[cur["in_reply_to"]], hops + 1
            key = cur.get("message_id") or normalize_subject(cur.get("subject") or "")
            g = roots.setdefault(
                key,
                {"subject": cur.get("subject"), "root_url": cur.get("archived_at"),
                 "count": 0, "first": None, "last": None},
            )
            g["count"] += 1
            d = m.get("date") or ""
            g["first"] = min(filter(None, [g["first"], d]), default=d) or None
            g["last"] = max(filter(None, [g["last"], d]), default=d) or None
        trows = sorted(roots.values(), key=lambda g: (g["first"] or "", g["root_url"] or ""))
        md = [HEADER + "# www-style thread summary (mirrored messages only)", "",
              "`first date | msgs | subject | root`", ""]
        md += [
            f"- {(g['first'] or '?')[:10]} | {g['count']} | {g['subject']} | {g['root_url']}"
            for g in trows
        ]
        (GEN / "www-style-threads.md").write_text("\n".join(md) + "\n")

    # --- by-spec digests
    open_by_label = Counter()
    for r in issues_rows:
        if r["state"] == "open" and r["kind"] == "issue":
            for l in r["labels"]:
                open_by_label[l] += 1
    for label, entries in sorted(by_spec.items()):
        entries.sort()
        lines = [HEADER + f"# {label} — chronological digest", ""]
        lines += [f"- {d} {text}" for d, text in entries]
        (GEN / "by-spec" / f"{label}.md").write_text("\n".join(lines) + "\n")

    # --- spec-status-index (needs w3c-api snapshots)
    md = [
        HEADER + "# Spec status index",
        "",
        "`shortname | maturity | latest TR | open issues | wiki page`",
        "",
    ]
    for f in sorted(W3C.glob("*.json")):
        spec = json.loads(f.read_text())
        vs = spec.get("versions") or []
        latest = vs[-1] if vs else {}
        short = spec["shortname"]
        wiki_page = (ROOT / "wiki" / "specs" / f"{short}.md").exists()
        md.append(
            f"- {short} | {latest.get('maturity', 'ED')} | {latest.get('date', '-')} | "
            f"{open_by_label.get(short, 0)} open | {'yes' if wiki_page else 'no'}"
        )
    (GEN / "spec-status-index.md").write_text("\n".join(md) + "\n")

    # --- people activity + unmapped
    sys.path.insert(0, str(Path(__file__).parent))
    from extract_people import load_people  # noqa: E402

    people = load_people()
    mapped = set()
    for p in people:
        mapped.add(p.get("github", "").lower())
        mapped.update(n.lower() for n in p.get("irc_nicks", []))
    arows = [
        {"key": k, **dict(sorted(v.items()))}
        for k, v in sorted(activity.items(), key=lambda kv: (-sum(kv[1].values()), kv[0]))
    ]
    (GEN / "people-activity.jsonl").write_text(jsonl(arows))
    unmapped = [
        f"{sum(v.values()):6d}  {k}"
        for k, v in sorted(activity.items(), key=lambda kv: (-sum(kv[1].values()), kv[0]))
        if k.lower() not in mapped and k != BOT and not k.endswith("[bot]")
    ][:200]
    (GEN / "people-unmapped.txt").write_text("\n".join(unmapped) + "\n")

    # --- sanity check (github-mirror baseline is source-scoped: email additions
    #     must not mask a bot-extraction regression)
    n_email = len(email_resolutions)
    print(
        f"[build_indexes] {len(files)} mirror files, {len(resolutions)} resolutions "
        f"({n_email} from minutes emails, {len(minutes_rows)} minutes mails), "
        f"{resolved_issue_count} github items with RESOLVED (baseline {EXPECTED_RESOLVED_ISSUES}), "
        f"{len(mrows)} meeting dates"
    )
    if resolved_issue_count < EXPECTED_RESOLVED_ISSUES:
        print(
            "[build_indexes] WARNING: fewer RESOLVED items than the 2026-07 baseline "
            "— extraction regex or mirror likely regressed"
        )


if __name__ == "__main__":
    main()
