#!/usr/bin/env python3
"""Generate wiki/people/<slug>.md from tools/data/people.yml + _generated/people-activity.jsonl.

people.yml uses a restricted YAML subset (documented in the file header); load_people()
is the only parser and is also imported by build_indexes.py. Generated pages must not
be hand-edited — extend people.yml and rerun.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PEOPLE_YML = ROOT / "tools" / "data" / "people.yml"
ACTIVITY = ROOT / "_generated" / "people-activity.jsonl"
OUT = ROOT / "wiki" / "people"

LIST_RE = re.compile(r"^\[(.*)\]$")


def load_people() -> list[dict]:
    people, cur = [], None
    for raw in PEOPLE_YML.read_text().splitlines():
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if line.startswith("- slug:"):
            cur = {"slug": line.split(":", 1)[1].strip()}
            people.append(cur)
        elif cur is not None and line.startswith("  ") and ":" in line:
            k, _, v = line.strip().partition(":")
            v = v.strip()
            m = LIST_RE.match(v)
            if m:
                items = [i.strip() for i in m.group(1).split(",") if i.strip()]
                cur[k] = items
            else:
                cur[k] = v
    return people


def activity_map() -> dict:
    if not ACTIVITY.exists():
        return {}
    rows = [json.loads(l) for l in ACTIVITY.read_text().splitlines() if l.strip()]
    return {r["key"].lower(): r for r in rows}


def render(p: dict, act: dict) -> str:
    keys = [p.get("github", "")] + p.get("irc_nicks", [])
    issues = sum(act.get(k.lower(), {}).get("issues_authored", 0) for k in keys if k)
    comments = sum(act.get(k.lower(), {}).get("comments", 0) for k in keys if k)
    irc = sum(act.get(k.lower(), {}).get("irc_lines", 0) for k in keys if k)
    nicks = ", ".join(f"`{n}`" for n in p.get("irc_nicks", [])) or "-"
    roles = "".join(f"- {r}\n" for r in p.get("roles", [])) or "- (none recorded yet)\n"
    return f"""---
name: {json.dumps(p.get('name'))}
slug: {p['slug']}
kind: person
github: {json.dumps(p.get('github'))}
irc_nicks: {json.dumps(p.get('irc_nicks', []))}
affiliation: {json.dumps(p.get('affiliation'))}
generated_by: llm
---

# {p.get('name')}

- GitHub: [@{p.get('github')}](https://github.com/{p.get('github')})
- IRC nicks: {nicks}
- Affiliation: {p.get('affiliation') or 'unknown'} *(verify against `raw/data/w3c-api/group/css/participants.json` before citing)*

## Roles

{roles}
## Activity in the mirror

Issues authored: {issues} / comments: {comments} / IRC minute lines: {irc}
(from `_generated/people-activity.jsonl`)

---

*Generated by `tools/extract_people.py` from `tools/data/people.yml` — do not hand-edit; extend the YAML and regenerate.*
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    people = load_people()
    act = activity_map()
    slugs = set()
    for p in people:
        slugs.add(p["slug"])
        (OUT / f"{p['slug']}.md").write_text(render(p, act))
    # remove pages whose yml entry disappeared
    for f in OUT.glob("*.md"):
        if f.stem not in slugs:
            f.unlink()
    print(f"[extract_people] {len(people)} people pages generated")


if __name__ == "__main__":
    main()
